---
title: ""
author: ""
date: ""
output:  html_document
      
---
```{r, echo = FALSE}
htmltools::includeHTML("index.html")
```

```{r code, include = FALSE}
library(tidyverse)
library(factoextra)
library(factoextra)
library(NbClust)
library(readxl)
library(plotly)
library(RColorBrewer)
library(ggplot2)
IscrittiAteneiItaliani<-read.csv2("http://dati.ustat.miur.it/dataset/3dd9ca7f-9cc9-4a1a-915c-e569b181dbd5/resource/32d26e28-a0b5-45f3-9152-6072164f3e63/download/iscrittixateneo.csv")
IscrittiAteneiItaliani$SommaIscritti<-IscrittiAteneiItaliani$Isc_M+IscrittiAteneiItaliani$Isc_F
IscrittiAteneiItaliani$AnnoA<-str_remove(IscrittiAteneiItaliani$AnnoA,"/.*")
IscrittiAteneiItaliani$SommaIscritti
MediaIscrittiMatrice<-aggregate(IscrittiAteneiItaliani$SommaIscritti~IscrittiAteneiItaliani$AteneoCOD, FUN = mean,data=IscrittiAteneiItaliani)
colnames(MediaIscrittiMatrice)[1] <- "Ateneo"
colnames(MediaIscrittiMatrice)[2] <- "MediaIscritti"
MediaIscritti<-data.frame(MediaIscrittiMatrice$MediaIscritti)
```
```{r elbow, fig.align="center", echo = FALSE}
# Elbow method
fviz_nbclust(MediaIscritti, kmeans, method = "wss") +
  geom_vline(xintercept = 4, linetype = 2)+
  labs(subtitle = "Elbow method")
```
```{r code2, include = FALSE}
# Silhouette method
fviz_nbclust(MediaIscritti, kmeans, method = "silhouette")+
  labs(subtitle = "Silhouette method")
# Gap statistic
# nboot = 50 to keep the function speedy. 
# recommended value: nboot= 500 for your analysis.
# Use verbose = FALSE to hide computing progression.
set.seed(123)
fviz_nbclust(MediaIscritti, kmeans, nstart = 25,  method = "gap_stat", nboot = 50)+
  labs(subtitle = "Gap statistic method")
#KMEAN Clusterization
KM=kmeans(MediaIscritti,4)
#Clusters
Cluster<-KM$cluster
MediaIscrittiMatrice$cluster<-Cluster
#Centers of the clusters
Centroidi<-data.frame(KM$centers)
colnames(Centroidi)[1] <- "Centroidi Cluster"
desc=c("Grande Ateneo","Piccolo Ateneo","Medio Ateneo","Mega Ateneo")
IdCluster=c(1,2,3,4)
Centroidi$desc<-desc
Centroidi$cluster<-IdCluster
DatiPerGrafico<-merge(MediaIscrittiMatrice, Centroidi, by = "cluster")
fig<-ggplot(DatiPerGrafico) +
  aes(x = `Centroidi Cluster`, y = MediaIscritti, colour = desc, text=paste0("Ateneo = ",Ateneo)) +
  geom_point(shape = "circle open", 
             size = 1.5) +
  scale_color_brewer(palette = "RdYlBu", direction = -1) +
  coord_flip() +
  theme_light()+labs(title="Cluster delle universita italiane per media di iscritti nel periodo 2010/2020",color='Legenda dei cluster')+
  theme(legend.title = element_text(color = "blue",size = 10,))
```

```{r, echo=FALSE}
htmltools::includeHTML("DataViz.html")
```

```{r graph, fig.align="center",echo=FALSE}
pp <-ggplotly(fig, width=700, height=600 )%>% config(displayModeBar = F)
ppc <- htmltools::div( pp, align="center" ) 
ppc
```

```{r codeDBScan, include = FALSE}
#DBSCAN Clusterization



NormIscritti<-as.data.frame(scale(MediaIscritti))

#DBScane k choice
dbscan::kNNdistplot(MediaIscritti, k =  4)
abline(h = 1500, lty = 2)


DBScanData <- fpc::dbscan(MediaIscritti, eps = 1500, MinPts = 4)
DBScanData$cluster
MediaIscrittiMatriceNorm<-MediaIscritti
colnames(MediaIscrittiMatriceNorm)[1] <- "Data"
MediaIscrittiMatriceNorm$clusterDBScan<-DBScanData$cluster



desc2=c("Mega Ateneo","Piccolissimo Ateneo","Piccolo Ateneo","Medio Ateneo","Grande Ateneo")
IdCluster2=c(0,1,2,3,4)
DBscanDesc<-data.frame(desc2)
DBscanDesc$cluster<-IdCluster2

MediaIscrittiMatriceNorm<-merge(MediaIscrittiMatriceNorm, DBscanDesc, by.x = "clusterDBScan",by.y = "cluster")
#DBSCAN plot


plotDB<-ggplot(MediaIscrittiMatriceNorm) +
 aes(x = Data, y = clusterDBScan, colour = desc2, size = Data) +
 geom_point(shape = "diamond") +
 scale_color_hue(direction = 1) +
 labs(x = "Numero Iscritti", y = "Cluster", title = "Risultati cluster DB Scan", 
 color = "Dimensione ateneo", size = "") +
 theme_light() +
 theme(plot.title = element_text(size = 16L, 
 face = "bold", hjust = 0.5))
```

```{r, echo=FALSE}
htmltools::includeHTML("DBScanIntroduzione.html")
```

```{r graphDbScan, fig.align="center",echo=FALSE}
pp2 <-ggplotly(plotDB, width=700, height=600 )%>% config(displayModeBar = F)
ppc2 <- htmltools::div( pp2, align="center" ) 
ppc2
```
<center>
Di seguito viene riportato l'andamento del personale accademico totale operante nel settore "Ingegneria industriale e dell'informazione" nelle universita' italiane per genere, anno e ruolo.

```{r, echo=FALSE}
ProfAteneiItaliani<-read.csv2("http://dati.ustat.miur.it/dataset/a60a221d-1c0d-4abb-bc8b-2199f61c205d/resource/92f2008d-958f-4e9c-ae5c-7a3dd418cd57/download/bdg_serie_academic_staff_ambito.csv")
datiProf<-ProfAteneiItaliani %>% filter(CODICE_ATENEO=="TTTTT")


graficoAndIng<-datiProf %>%
 filter(AREA_SD %in% "09 - Ingegneria industriale e dell'informazione") %>%
 filter(FoRD %in% 
 "02 - Engineering and technology") %>%
 ggplot() +
 aes(x = ANNO, y = N_AcStaff, colour = GENERE) +
 geom_line(size = 0.5) +
 scale_color_hue(direction = 1) +
 labs(x = "Anno di riferimento", y = "Numero di personale attivo", title = "Andamento numero del personale totale attivo in Italia", 
 subtitle = "Area SD : Ingegneria Industriale e dell'informazione", color = "Genere") +
 theme_minimal() +
 theme(plot.title = element_text(size = 15L, face = "bold", hjust = 0.5), plot.subtitle = element_text(face = "italic", 
 hjust = 0.5)) +
 facet_wrap(vars(DESC_QUALIFICA), scales = "free")


ggplotly(graficoAndIng,width = 1080, height = 720)%>% config(displayModeBar = F)
```
</center>

```{r, echo=FALSE}
htmltools::includeHTML("footer.html")
```



